import Stripe from "stripe";

let _stripe: Stripe | null = null;

export function getStripe() {
  if (_stripe) return _stripe;
  const key = process.env.STRIPE_SECRET_KEY;
  if (!key) throw new Error("STRIPE_SECRET_KEY is not set");
  // Pin to the installed types' default API version. Cast to satisfy the literal type
  // generated by Stripe's SDK so consumers can upgrade without touching this file.
  _stripe = new Stripe(key, { apiVersion: "2025-02-24.acacia" as Stripe.LatestApiVersion });
  return _stripe;
}

export const STRIPE_CONFIGURED = !!process.env.STRIPE_SECRET_KEY;

export function priceIdFor(plan: "monthly" | "yearly") {
  return plan === "monthly"
    ? process.env.STRIPE_PRICE_MONTHLY!
    : process.env.STRIPE_PRICE_YEARLY!;
}

export function amountCentsFor(plan: "monthly" | "yearly") {
  const m = parseInt(process.env.SUBSCRIPTION_PRICE_MONTHLY_CENTS || "1500", 10);
  const y = parseInt(process.env.SUBSCRIPTION_PRICE_YEARLY_CENTS || "14400", 10);
  return plan === "monthly" ? m : y;
}

/**
 * Derive the (year, month) a Stripe invoice's payment should be attributed to.
 *
 * Pool funding has to match the *billing period the invoice covers*, not when
 * the user happens to pay. Otherwise a Dec invoice paid Jan 1 silently
 * under-counts the Dec draw.
 *
 * Precedence:
 *   1. line item period.start  — most precise (per-line accuracy)
 *   2. invoice.period_start    — invoice-wide billing period
 *   3. invoice.created         — issue date (last-resort fallback)
 */
export function invoicePeriod(invoice: Stripe.Invoice): {
  periodYear: number;
  periodMonth: number;
} {
  const linePeriodStart = invoice.lines?.data?.[0]?.period?.start;
  const ts =
    linePeriodStart ||
    (invoice as { period_start?: number }).period_start ||
    invoice.created ||
    Math.floor(Date.now() / 1000);
  const d = new Date(ts * 1000);
  return {
    periodYear: d.getUTCFullYear(),
    periodMonth: d.getUTCMonth() + 1,
  };
}
